# Generated by Django 3.0.5 on 2020-10-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubimage', models.ImageField(upload_to='logos/')),
                ('clubname', models.TextField()),
                ('clubtagline', models.TextField()),
                ('clubdesc', models.TextField()),
                ('clubpurp', models.TextField()),
                ('memsize', models.TextField()),
                ('nofevents', models.TextField()),
                ('clubactivities', models.TextField()),
                ('coreteam', models.TextField()),
                ('members', models.TextField(blank=True)),
            ],
        ),
    ]
