# Generated by Django 3.0.5 on 2020-10-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0003_auto_20201024_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='clubactivities',
        ),
        migrations.RemoveField(
            model_name='clubs',
            name='clubpurp',
        ),
    ]
