# Generated by Django 3.0.5 on 2020-10-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0004_auto_20201024_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='contact_mail',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubs',
            name='president',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
