# Generated by Django 3.0.5 on 2020-10-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0005_auto_20201024_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.TextField()),
                ('date', models.DateField()),
                ('amount', models.TextField()),
                ('source_name', models.TextField()),
                ('source_descip', models.TextField()),
                ('cred_deb', models.BooleanField()),
            ],
        ),
    ]
