# Generated by Django 3.0.5 on 2020-10-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0006_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='date',
            field=models.TextField(),
        ),
    ]
