# Generated by Django 3.0.5 on 2020-10-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0007_auto_20201029_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='cred_deb',
            field=models.TextField(),
        ),
    ]
