# Generated by Django 3.0.5 on 2020-05-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='clubactivities',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubs',
            name='clubdesc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubs',
            name='clubimage',
            field=models.ImageField(default=0, upload_to='logos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubs',
            name='clubpurp',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubs',
            name='clubtagline',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubs',
            name='coreteam',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubs',
            name='members',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='memsize',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubs',
            name='nofevents',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
